*Задание 1*
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [13]:
import pandas as pd
data =pd.read_csv('ratings.csv')
film =data.query('rating =={}'.format(5.0))
film['movieId'].value_counts().head(1)

318    39553
Name: movieId, dtype: int64

*Задание 2*
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [26]:
power_csv = pd.read_csv('power.csv')
filtered_1 = power_csv [((power_csv['country']=='Latvia') | (power_csv['country']=='Lithuania') | (power_csv['country']=='Estonia')) ]
filtered_2 = filtered_1[((filtered_1['quantity'] > 0) & (filtered_1['year'] >= 2005) & (filtered_1['year'] <= 2010) &((filtered_1['category'] ==4)| (filtered_1['category'] ==12) | (filtered_1['category'] ==21)))]
sum(filtered_2['quantity'])

240580.0

*Задание 3*
Выберите страницу любого сайта с табличными данными. Импортируйте таблицы в pandas dataframe.
Примеры страниц (необязательно брать именно эти):
https://fortrader.org/quotes
https://www.finanz.ru/valyuty/v-realnom-vremeni

In [27]:
pd.read_html('https://www.finanz.ru/valyuty/v-realnom-vremeni', encoding='utf-8')[1]

,Unnamed: 0,Рубль,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
0,NaN,GBP/RUB,1014880,-,1011254,"0,36 %",03626,06:22:00
1,NaN,EUR/RUB,916250,-,912570,"0,40 %",03680,06:22:00
2,NaN,USD/RUB,779796,-,776813,"0,38 %",02983,06:22:00
3,NaN,JPY/RUB,07407,-,07390,"0,23 %",00017,06:22:00
4,NaN,CNY/RUB,115962,-,115681,"0,24 %",00280,06:22:00
5,NaN,CHF/RUB,853877,-,850555,"0,39 %",03321,06:22:00
6,NaN,Евро,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
7,NaN,EUR/USD,11750,-,11749,"0,01 %",00001,06:22:00
8,NaN,EUR/GBP,09028,-,09027,"0,01 %",00001,06:22:00
9,NaN,EUR/JPY,1236955,-,1235000,"0,16 %",01955,06:22:00
10,NaN,EUR/CHF,10730,-,10729,"0,01 %",00001,06:22:00
11,NaN,Доллар США,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
12,NaN,USD/EUR,08510,-,08511,"-0,01 %",-00001,06:22:00
13,NaN,USD/GBP,07683,-,07682,"0,02 %",00002,06:22:00
14,NaN,USD/JPY,1052850,-,1051210,"0,16 %",01640,06:22:00
15,NaN,USD/CHF,09133,-,09133,"0,00 %",00000,06:22:00
16,NaN,Японская иена,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
17,NaN,JPY/EUR (100:1),08100,-,08100,"-0,16 %",00000,06:22:00
18,NaN,JPY/GBP,00073,-,00073,"-0,13 %",00000,06:22:00
19,NaN,JPY/USD,00095,-,00095,"-0,15 %",00000,06:22:00
20,NaN,JPY/CHF (100:1),08700,-,08700,"-0,15 %",00000,06:22:00
21,NaN,Фунт стерлингов,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
22,NaN,GBP/USD,13015,-,13016,"0,00 %",-00001,06:22:00
23,NaN,GBP/JPY,1370102,-,1368387,"0,13 %",01715,06:22:00
24,NaN,GBP/EUR,11076,-,11076,"0,00 %",00000,06:22:00
25,NaN,GBP/CHF,11886,-,11886,"0,01 %",00001,06:22:00
26,NaN,Швейцарский франк,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
27,NaN,GBP/CHF,11886,-,11886,"0,01 %",00001,06:22:00
28,NaN,EUR/CHF,10730,-,10729,"0,01 %",00001,06:22:00
29,NaN,JPY/CHF (100:1),08700,-,08700,"-0,15 %",00000,06:22:00
30,NaN,USD/CHF,09133,-,09133,"0,00 %",00000,06:22:00
31,NaN,Украинская гривна,Предложение,Спрос,Предыдущее закрытие,%,Абсолютное значение,Время
32,NaN,EUR/UAH,333009,-,332981,"0,01 %",00028,06:22:00
33,NaN,USD/UAH,283400,-,283400,"0,00 %",00000,06:21:00
34,NaN,CHF/UAH,310337,-,310303,"0,01 %",00034,06:22:00
35,NaN,GBP/UAH,368845,-,368930,"-0,02 %",-00085,06:22:00

*Задание 4*
Напишите функцию, которая классифицирует фильмы из материалов занятия по следующим правилам:
- оценка 2 и меньше - низкий рейтинг
- оценка 4 и меньше - средний рейтинг
- оценка 4.5 и 5 - высокий рейтинг

Результат классификации запишите в столбец class

In [28]:
data = pd.read_csv('ratings.csv')
data_low = data.loc[data['rating'] <=2].copy()
data_low['class'] = 'низкий рейтинг'
data_average = data.loc[(data['rating']>2)& (data['rating'] <=4)].copy()
data_average['class'] = 'средний рейтинг'
data_high = data.loc[(data['rating']==4.5) | (data['rating']==5)].copy()
data_high['class'] = 'высокий рейтинг'
new_data = pd.concat([data_low, data_average,data_high], ignore_index = True)
new_data

          userId  movieId  rating   timestamp            class
0              1     5269     0.5  1147879571   низкий рейтинг
1              1     5684     2.0  1147879797   низкий рейтинг
2              1     7318     2.0  1147879850   низкий рейтинг
3              1     8685     1.0  1147878023   низкий рейтинг
4              2       62     0.5  1141417130   низкий рейтинг
...          ...      ...     ...         ...              ...
25000090  162541     8983     4.5  1240953211  высокий рейтинг
25000091  162541    31658     4.5  1240953287  высокий рейтинг
25000092  162541    45517     4.5  1240953353  высокий рейтинг
25000093  162541    50872     4.5  1240953372  высокий рейтинг
25000094  162541    63876     5.0  1240952515  высокий рейтинг

[25000095 rows x 5 columns]

*Задание 6*
Есть мнение, что “раньше снимали настоящее кино, не то что сейчас”. Ваша задача проверить это утверждение, используя файлы с рейтингами фильмов из прошлого домашнего занятия (файл ratings.csv из базы https://grouplens.org/datasets/movielens). Т. е. проверить верно ли, что с ростом года выпуска фильма его средний рейтинг становится ниже.

При этом мы не будем затрагивать субьективные факторы выставления этих рейтингов, а пройдемся по следующему алгоритму:

В переменную years запишите список из всех годов с 1950 по 2010.

Напишите функцию production_year, которая каждой строке из названия фильма выставляет год выпуска. Не все названия фильмов содержат год выпуска в одинаковом формате, поэтому используйте следующий алгоритм:

для каждой строки пройдите по всем годам списка years
если номер года присутствует в названии фильма, то функция возвращает этот год как год выпуска
если ни один из номеров года списка years не встретился в названии фильма, то возвращается 1900 год
Запишите год выпуска фильма по алгоритму пункта 2 в новый столбец ‘year’

Посчитайте средний рейтинг всех фильмов для каждого значения столбца ‘year’ и отсортируйте результат по убыванию рейтинга

In [31]:
year =list(range(1950, 2011))
data =pd.read_csv('movies.csv')
data['year'] = 1
def year_num(st):
    for i in year:
        if str(i) in st:
            return i
    return 1900
for i in range(len(data)):
    y = year_num(data.loc[i]['title'])
    data['year'].loc[i]=y
data_csv = pd.read_csv('ratings.csv') 
data_csv = data_csv.groupby('movieId').mean()['rating']
data = data.set_index('movieId').join(data_csv)
data.groupby('year').mean().sort_values('rating',ascending = False)

        rating
year
1963  3.228859
1961  3.208200
1962  3.194438
1953  3.190671
1950  3.179434
...        ...
1991  2.973292
1990  2.955692
1987  2.941741
1989  2.934094
1988  2.908508

[62 rows x 1 columns]

C ростом года выпуска фильма его средний рейтинг становится ниже, значит, мнение “раньше снимали настоящее кино, не то что сейчас” , верно.